# Generated by Django 4.0.4 on 2022-08-29 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(20)]),
        ),
    ]
